CREATE DATABASE board;

CREATE TABLE topic(
    id INT(11) NOT NULL AUTO_INCREMENT,
    title VARCHAR(30) NOT NULL,
    description TEXT NOT NULL,
    created TIMESTAMP NOT NULL,
    user_id INT NOT NULL,
    PRIMARY KEY(id)
);

CREATE TABLE user(
    u_id INT(11) NOT NULL AUTO_INCREMENT,
    id VARCHAR(20) NOT NULL,
    pw VARCHAR(15) NOT NULL,
    re_pw VARCHAR(15) NOT NULL,
    PRIMARY KEY(id)
);
